# Generated by Django 4.0.4 on 2022-06-04 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mytweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='like',
            new_name='likes',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Fname', models.CharField(blank=True, max_length=20, null=True)),
                ('Lname', models.CharField(blank=True, max_length=30, null=True)),
                ('CountryOfOrigin', models.CharField(blank=True, max_length=30, null=True)),
                ('LikedTweets', models.ManyToManyField(related_name='userLikes', to='mytweet.tweet')),
                ('OwnTweets', models.ManyToManyField(related_name='userTweets', to='mytweet.tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
