# Generated by Django 4.1.7 on 2023-03-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytweet', '0008_chat_room_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.TextField(),
        ),
    ]
